### ISSUE TITLE
kLastUsedTimeKey is defined twice

### ISSUE THREAD

**Issue by p2** [ResearchKit/AppCore#15]
To keep track of last time the app was used, the app delegate sets `kLastUsedTimeKey` on termination/moving to background. APCTabBarViewController does the same – with the same key that it defines itself – when PIN entry succeeds.

It seems the tab controllers implementation can be removed entirely. If not it should probably be moved to the delegate method that the app delegate implements and the define should be removed.

**Comment by jwe-apple** [comment]
@p2 Please submit that as a pull request. Even if we don't accept it, I'd like it more visible.

**Comment by peculiar** [comment]
Capturing the `kLastUsedTimeKey` on termination and backgrounding is not sufficient in order to enable autolock feature. The `kLastUsedTimeKey` is _not_ captures if the user deletes the app from the Recently Used list. As such, the date the user was authenticated becomes a good approximation of the _last used_ timestamp.

**Comment by p2** [comment]
Alright, then capturing this timestamp can be moved to the AppDelegate's delegate method implementation.

**Comment by peculiar** [comment]
Agreed, the timestamp capture can be moved to `passcodeViewControllerDidSucceed:viewController`.
