### ISSUE TITLE
Add documentation for AppCore

### ISSUE THREAD

**Issue by drefiuza** [ResearchKit/AppCore#40]
Are there plans to include documentation on how to integrate AppCore into a fresh project—or perhaps a demo app similar in purpose to ORKCatalog, showcasing a generic app using AppCore?

**Comment by jwe-apple** [comment]
Possibly. AppCore's API etc is very much in flux now. When / if it stabilizes then I imagine we will. Re-naming this issue, and we'll use it to track.

**Comment by drefiuza** [comment]
Makes sense. Thanks!

**Comment by skoth001** [comment]
is there any update on this issue?

**Comment by evliu** [comment]
+1 on update on issue [:

**Comment by apbendi** [comment]
I'm also curious on this. Is AppCore even intended to be the basis for new projects? Is there any documentation or any tutorials on how to get started with using it. Lots of resources out there for ResearchKit, but I'm not seeing much for AppCore! Thanks!

**Comment by YuanZhu-apple** [comment]
https://github.com/ResearchKit/AppCore/blob/master/README.md

"We are excited about how helpful AppCore has been in the development of several ResearchKit apps. In order to help the ResearchKit community derive the most utility from the individual components in AppCore, we’re working hard with many developers to transition components of AppCore into the main ResearchKit repo. As a result, we will only be accepting bug fixes to AppCore moving forward and hope you’ll continue giving feature and UI enhancements once the pieces are fully integrated into ResearchKit’s repo."

**Comment by apbendi** [comment]
Thanks @YuanZhu-apple, appreciate the response! If you're willing to expand on that at all, I'd appreciate it. For example, will the stated AppCore features, such as data storage and adapters for backend services (like sage) be supported in ResearchKit itself? Can you give any guidance on that status of such features or when we might expect any of them to land on stable?

Thanks again!

**Comment by YuanZhu-apple** [comment]
@apbendi When you are talking about `data storage` feature, are expecting a storage to temporally store the collected results/data before the uploading is finished?  

And for backend support, what do you need beside `Sage's iOS SDK`?

**Comment by apbendi** [comment]
Thanks again @YuanZhu-apple! Here's what I mean: AppCore's features are listed as follows.

> - Dashboard with progress graph
> - Data storage back end
> - JSON serialization and deserialization
> - Integration with Sage Bionetworks' Bridge service

Certainly it would be possible to create a vanilla ResearchKit app, build a persistence layer, a custom Dashboard, and pull in the Sage Bridge SDK to communicate with their backend. But why reinvent the wheel if AppCore already does this?

Well, one reason might be that AppCore isn't documented, and/or is too coupled to the apps it was initially created with, and isn't going to be supported going forward. My initial take is that this might be the case. If so, fine, no worries. At least I know what approach to take!

If AppCore does have some documentation I haven't found, or if some of the features listed above will be pulled into ResearchKit proper in one way or another, it would be good to know this too! Just trying to weigh options. Any info you can provide is helpful. Thanks for your time!

**Comment by YuanZhu-apple** [comment]
AppCore is not maintained, and is not built on the top of latest ResearchKit. 

My recommendations for replacements of AppCore's features:
1. Dashboard - Use the chart library in RK: http://researchkit.org/docs/docs/Charts/ChartsAndGraph.html
2. Data storage - We are working on a pre upload storage
3. JSON serialization and deserialization - https://github.com/ResearchKit/ResearchKit/blob/master/Testing/ORKTest/ORKTest/ORKESerialization.h
4. Integration with Sage Bionetworks' Bridge service - Just use Sage's SDK, since it is maintained by Sage.

Also checkout the new sample app for current ResearchKit's capability: https://github.com/ResearchKit/ResearchKit/tree/master/samples/ORKSample/ORKSample

Hope you find this is helpful.

**Comment by apbendi** [comment]
Thanks @YuanZhu-apple, this is indeed very helpful! I appreciate you taking the time to respond and to provide additional resources. Perhaps it would be worth considering adding something similar to the readme? All the best!
